### PR TITLE
makes button CSS class dynamic

### PR DESCRIPTION
**Pull request by aftertaf**
adding 'button_css' plugin configuration parameter (usage) in PHP code rendering button on front-end.
requires modification of supersaas.xml to add the new configuration property

### CODE REVIEW

**Comment by Fjan** [comment]
Thank you for the suggestion. Adding a setting is a lot more work for us, as it needs to be translated into ten languages, and my guess is only very few people will need to adjust the class name, so I hope you don't mind if we do not accept this one.

**Comment by aftertaf** [comment]
Ok no worries. Mine works fine on my personal 'fork'...
I don't mind Google translating the backend descriptions for the other languages, but it is your baby, your call 🤙

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Fjan** [comment]
Thank you for your understanding :+1:

**Comment by aftertaf** [comment]
All good!
I do have a 'support' question re credits' functionality that I would like to discuss with you or your team.
I'll wait for the feedback from the initial mail.
Great job with your product!
David / aftertaf.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Fjan** [comment]
I don't see any open support requests relating to credits at this time, did you send it to support@supersaas.com ?

**Comment by aftertaf** [comment]
Yeah via the contact form.
Never mind I will write up what I am trying to achieve and the process that I am imagining, and will send to the contact mail.
Hopefully it won't come across as too random 😎😊

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Fjan** [comment]
Ok, we should reply to everything submitted via the contact form within 15 minutes, please resubmit if you haven't received a reply

**Pull request closed without merging**
